#3282 BleService
openmsupply/mobile pull request #3284
Opened 2020-12-09 20:44 UTC by joshxg

Fixes #3282 

## Change summary

- Adds `BleService` class.

## Testing

- [ ] ???

### Related areas to think about

- This was taken from [mSupply ColdChain](https://raw.githubusercontent.com/openmsupply/msupply-cold-chain/develop/src/common/services/Bluetooth/BleService.js) with some minor adjustments - comments mainly.
- This has never been reviewed by anyone

2020-12-10 06:20 UTC, joshxg commented
Have updated with @Chris-Petty 's develop fix

2020-12-16 05:10 UTC, katherine-sussol requested changes
Sorry for the slow response, took me a while to get my bearings! 

I think it might be useful to be able to mock some part of the Bluetooth behaviour to allow (manual) testing of application code/UI without the dependency - and also so it runs (at least at a basic level) on an emulator (maybe separate issue/PR though?). 

Don't really know the best way or how to do this yet, MockBleManager that gets injected if debug/dev? 

Aside from that, the BleService methods seem to be working as expected with the suggested changes 🥳

2020-12-16 10:28 UTC, joshxg commented on src/bluetooth/BleService.js
> +    this.manager.connectToDevice(macAddress, { scanMode: BLUETOOTH.SCAN_MODE.LOW_LATENCY });
Nice!

2ac6294e1fd0a1a1ccc971a18746d6412e5cfca7

2020-12-16 10:29 UTC, joshxg commented on src/bluetooth/BleService.js
> +        BLUETOOTH.SERVICE.UUID,
🤣 

a2ee3ba18aacf5b30b7eec857782abdcc5b3f763

2020-12-16 10:29 UTC, joshxg commented on src/bluetooth/BleService.js
> +      await this.manager.cancelDeviceConnection(macAddress);
Nope - just me being weird

ccfa5927431c95928e3a4f4187122b95c7270e0b

2020-12-16 10:30 UTC, joshxg commented on src/bluetooth/BleService.js
> +   * @param {Int} logInterval
"hate" is a strong word 🤣 

a91c19c056e1876b36694cda314a284331438cce

2020-12-16 10:30 UTC, joshxg commented
Nice, thanks a lot. Glad you took the time!

2020-12-16 10:34 UTC, joshxg commented
Have this impl :

https://github.com/openmsupply/msupply-cold-chain/blob/develop/src/common/services/Bluetooth/DevBleManager.js

Which utilized like this: https://github.com/openmsupply/msupply-cold-chain/blob/43f882c09732480d4b211536b98b2561de803070/src/ui/containers/DependencyContainer.js#L44

So can just construct the instance of the ble with a different manager dependency. As much as I don't like mocks, it's pretty required for this!

2020-12-16 22:03 UTC, katherine-sussol approved these changes
![Dog Human Fashion](https://media.giphy.com/media/gLuP6eGC3yamBoGMJT/giphy.gif)

2020-12-17 02:02 UTC, joshxg commented
😍

2020-12-17 02:02 UTC, merged