#3440 duration stepper unusable
openmsupply/mobile pull request #3441
Opened 2021-02-02 02:39 UTC by mark-prins

Fixes #3440 

## Change summary

Changed the duration stepper and storage to use minutes. The display and user interaction is in minutes, it seems clumsy to work around this and store in seconds.

Have updated the usage to reflect what I think it should be.. though I'm not entirely sure about that

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Add a sensor, adjust duration.
- [ ] Default should show `20` for a new sensor
- [ ] minimum value of `1` is enforced

### Related areas to think about

The usage which, I think, was comparing milliseconds against (n seconds / 1000). That would mean a configured value of 20 minutes would be stored as 1200 ( i.e. in seconds ) and then used as ```logsDuration < 1200 / 1000``` ??

2021-02-02 02:39 UTC, mark-prins commented on src/bluetooth/BreachManager.js
> +    if (logsDuration < duration * MILLISECONDS.ONE_MINUTE) return false;
This is the line I need confirmation on.

2021-02-02 02:49 UTC, joshxg requested changes
You're right. There's plenty of weird inconsistencies I've been noticing :(

Unfortunately there's a bunch of desktop work which assumes duration is in seconds. The UI for TBConfigs, as well as on `TemperatureBreach` the `duration` is 'copied' over so in that form also.

![image](https://user-images.githubusercontent.com/35858975/106545116-ad674900-656d-11eb-813d-a19fc7828e72.png)

Additionally the `BleService` method `updateLogInterval`

```
  updateLogInterval = async (macAddress, logInterval) => {
    await this.connectAndDiscoverServices(macAddress);
    return this.writeWithSingleResponse(
      macAddress,
      `${BLUETOOTH.COMMANDS.UPDATE_LOG_INTERVAL}${logInterval}`,
      stringFromBase64
    );
  };
``` 

The BlueMaestro sensors use the command `*lintXXX` (I believe it is 60-6535 and the original inspiration duration is in seconds), will need to be changed.

I'm not opposed to changing duration to seconds (will also require minor changes to CCA), if we want to do this work.

2021-02-02 02:51 UTC, joshxg commented
Think I didn't emphasise enough that I really want to make it minutes - also not sure if Dhanya will blow a gasket if I do a desktop PR

2021-02-02 02:54 UTC, joshxg commented
OH - I am getting completely confused between log intervals and breach config durations!!!!!

2021-02-02 21:02 UTC, mark-prins commented
Thanks @joshxg - that validates the logic in the `BreachManager`. I've also commented to clarify.
I'll change to milliseconds and try to get the UI to work, I don't see that we have time to make big changes right now.. but we do need the UI to be usable.

This also affects the logInterval then? as that was changed to use minutes to get it working in another PR

2021-02-02 21:05 UTC, joshxg commented
That's where the mess becomes very obvious! Log interval should be in seconds. So yeah, saved persistently as seconds but displayed as minutes

2021-02-02 22:02 UTC, mark-prins commented
Ready to review again. Now storing duration as milliseconds, while displaying as minutes.
Tests updated and code commented.

2021-02-03 05:48 UTC, joshxg approved these changes
Nice !

I merged develop in and also made this commit (cause I had it sitting staged to get the sensor edit page to work) - 57ddd28 - Seems to work perfectly! Thanks so much

2021-02-03 06:08 UTC, joshxg commented
🤞 hope that commit was OK 🤣

2021-02-03 06:08 UTC, merged