Add update to reducers to use only plain objects, and the initialState function when resetting
openmsupply/mobile pull request #3444
Opened 2021-02-02 04:38 UTC by joshxg

Fixes #3434

## Change summary

- Primarily this is hooking up `SensorEditPage` up to use `SensorReducer`, `TemperatureBreachConfigReducer` and `LocationReducer` instead of `SensorDetail`. When you put it in a sentence like this, it doesn't seem 'simpler' ...!
- It adds the functionality that a sensor is actually saved once clicking 'save'. Technically, it will save the temperature breach configs, the location and the sensor, after sending commands to the sensor.
- Can/should be optimized to only save/send commands for what is needed

## Testing

- [ ] Edit a sensor: The location is edited (the sensor code field is really a location code field), and the configs which are related to the location which is related to the sensor is saved.

### Related areas to think about

- Really not sure what to do about this 'hidden' location situation

2021-02-02 05:11 UTC, joshxg commented on src/reducers/Entities/LocationReducer.js
> +});
This is the weirdest? part of the PR I think.

- Realm objects can't be spread, so if there was a redux object, trying to edit immutably is a pain.
- Using realm `toJSON` results in an object which has clones of all of the related records also, so if you are to use `update` on the resulting object which has been edited, the potentially stale and related `sensor` would also be saved.
- ONLY using realm objects results in live updates and requires more complex rolling back (as we update after a 'save' button is clicked - this is the same as in the new sensor flow).

So, I decided to take this route, and transform the objects into plain, simple JS objects in the redux store.

Another alternative would be to override `toJSON` in the `Sensor` realm class.

side note: Possibility here to create an abstraction to hide realm implementation such that we use plain JS objects by overriding `toJSON` on all of the realm classes and pass it through the abstraction to be persisted as whatever. Good phase1 of 2 for implementing sqlite.

2021-02-03 22:12 UTC, mark-prins requested changes
I saved an existing sensor and the app crashed with `null is not a valid Bluetooth address`
looking into it now.

Also had this warning `Warning: Failed prop type: The prop 'lastSyncDate' is marked as required in 'SensorEditPageComponent', but its value is 'undefined'.`

2021-02-03 22:20 UTC, mark-prins commented
@joshxg The method `updateSensor` is expecting a `sensor` parameter, but is getting passed `macAddress, logInterval`

2021-02-03 22:25 UTC, joshxg commented
@mark-prins Argh - sorry. I messed this up in the merge.

I changed the params in this commit: [`5ea154e` (#3444)](https://github.com/openmsupply/mobile/pull/3444/commits/5ea154e4161b9322c75be275cfb899680eb544db)

I thought since `updateLogInterval` only required the `macAddress` and `logInterval` and `disable` only required the `macAddress` it might be more explicit to pass those exact params rather than the more obscure 'sensor' object.. but maybe that's silly?

2021-02-03 22:36 UTC, katherine-sussol commented on src/pages/SensorEditPage.js
> +    dispatch(TemperatureBreachConfigActions.update(id, 'duration', value * 60));
I noticed something a little odd with the duration decrementor as well (I don't think it was necessarily introduced here - but it's just visible in realm now that it's actually saving), in that I'm able to decrement below 0 duration (but shows '1 minute' in the UI). Have been digging around to see if I could find the culprit but maybe better for a separate issue?

2021-02-03 22:39 UTC, joshxg commented on src/reducers/Entities/LocationReducer.js
> +});
Just something like this in a realm class:

```
toJSON(){
	return { this.id ... }
}
```


Bring on sqlite and working with plain js objects 🤷 

renamed and a brief comment: 064e355

2021-02-03 22:40 UTC, joshxg commented on src/pages/NewSensor/NewSensorStepThree.js
> +          onPress={() => withLoadingIndicator(connectToSensor(macAddress, logInterval))}
Sorry! c9e967a

Big merge :(

2021-02-03 22:40 UTC, joshxg commented on src/pages/SensorEditPage.js
> +    dispatch(TemperatureBreachConfigActions.update(id, 'duration', value * 60));
you're right - the merge again I tells ya 
b3d6ddf

2021-02-03 22:40 UTC, joshxg commented on src/reducers/Entities/SensorReducer.js
> +  locationID: sensor.location.id,
9a243f8

2021-02-03 22:43 UTC, joshxg commented on src/pages/NewSensor/NewSensorStepThree.js
> +          onPress={() => withLoadingIndicator(connectToSensor(macAddress, logInterval))}
🙄 
92c24a6

2021-02-03 22:49 UTC, joshxg commented on src/pages/NewSensor/NewSensorStepThree.js
> +          onPress={() => withLoadingIndicator(connectToSensor(macAddress, logInterval))}
I give up 
b648ad8

2021-02-03 23:09 UTC, joshxg commented on src/pages/SensorEditPage.js
> +    dispatch(TemperatureBreachConfigActions.update(id, 'duration', value * 60));
nice! 

648cfe6

I just did it in a commit here (Also the change to the hook is semi-unrelated but ensures that if you use a picker i.e. the time picker the input updates correctly ....)

2021-02-03 23:44 UTC, mark-prins approved these changes

2021-02-04 00:05 UTC, merged