#3823 Pagination of patients in vaccine dispensing
openmsupply/mobile pull request #3826
Opened 2021-03-21 22:55 UTC by joshxg

Fixes #3823 

## Change summary

- This is pretty unnecessary, I think. Practically, the user is surely not going to be scroll through 100's of patients hoping to find the one, they would surely add more search details.. but here it is!
- It's not perfect- technically if you unmount in the middle of the fetch and there's no timeout for the request. This functionality is built in to `useFetch` but not really useable. I don't think we really have time to be making it perfect..
- I didn't add it to normal dispensing. Kinda don't want to 🤣 You get 50 patients.. surely you can just refine your search and it'll be OK for Tonga at least..

## Testing

- [ ] Have heaps of patients and do a lookup- you get 50 patients and then when you scroll down it does another lookup and gets you another 50

### Related areas to think about

N/A

2021-03-23 22:38 UTC, mark-prins commented
Just noticed that earlier comments were pending..

Testing this morning, changed the limit to `5` so I didn't have to create lots of patients.
It returned 5 patients, said that it was searching and then..

```
[Wed Mar 24 2021 11:34:57.630]  WARN     Possible Unhandled Promise Rejection (id: 1):
Error: No records found
processResponse@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:173118:40
processPatientResponse@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:173136:33
getMorePatients$
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25082:23
```

2021-03-23 22:42 UTC, mark-prins commented on src/widgets/Tabs/PatientSelect.js
> +    <FlexRow flex={1} justifyContent="center" alignItems="space-between">
```suggestion
    <FlexRow flex={1} justifyContent="center" alignItems="space-between" style={localStyles.more}>
```

2021-03-23 23:03 UTC, mark-prins commented on src/hooks/useLocalAndRemotePatients.js
> +        data: processPatientResponse({ ...getMoreResponse, json: await getMoreResponse.json() }),
`processPatientResponse` throws an error if there are no results.. which happens when we hit the end of the patient list. 
I think it should dispatch an action that keeps the current list of patients and sets `gettingMore: false`

2021-03-24 00:21 UTC, joshxg commented
Added styling here: 
3f0640f

Messing around with the state a bit more here: 
a1ae6b3

Still not perfect..  I really prefer to use https://react-query.tanstack.com/ for fetching stuff like this as it sure does have so many cases you need to account for but I guess with it just being a single area to do a request its OK.. it's already so confusing, totally going to add it if theres anything else needing to be added 🤣

2021-03-24 20:25 UTC, mark-prins commented on src/hooks/useLocalAndRemotePatients.js
> +    { data, loading, searchedWithNoResults, error, limit, offset, gettingMore },
```suggestion
    { data, loading, searchedWithNoResults, error, limit, offset, gettingMore, noMore },
```

2021-03-24 20:26 UTC, mark-prins commented on src/hooks/useLocalAndRemotePatients.js
> +  const { fetch, refresh, isLoading, response, error: fetchError, noMore } = useFetch(
```suggestion
  const { fetch, refresh, isLoading, response, error: fetchError } = useFetch(
```

2021-03-24 20:27 UTC, mark-prins commented
@joshxg cool - that's looking good

one more thing - the `noMore` should come from state, rather than fetch. the fetch is currently looping continuously

2021-03-24 20:55 UTC, mark-prins requested changes
just the conflict and the change of `noMore`

2021-03-24 22:13 UTC, joshxg commented
woah! whoooops!
63b1d95

2021-03-24 23:30 UTC, mark-prins approved these changes
👍

2021-03-25 05:06 UTC, merged