#3803 ADR Modal
openmsupply/mobile pull request #3851
Opened 2021-03-24 22:09 UTC by joshxg

Fixes #3803 

## Change summary

- Adds an ADR modal to create new ADRs

## Testing

**NOTE: Need some footrunner for an ADR form- will becoming soon**

- [ ] Can create a new ADR, save it and sync it to the server - checking in the record browser, all the fields are filled correctly
- [ ] Cannot create an ADR which is not valid

### Related areas to think about

2021-03-24 22:10 UTC, joshxg commented
used 

```
$formSchema:=ds.form_schema.all().first()



$adrSchema:=ds.form_schema.new()
$adrSchema.ID:=UUID_generate
$adrSchema.type:="ADR"
$adrSchema.json_schema:=$formSchema.json_schema
$adrSchema.ui_schema:=$formSchema.ui_schema
$adrSchema.version:=1
$adrSchema.save()
```

to just use my survey form

2021-03-24 22:11 UTC, joshxg commented
![image](https://user-images.githubusercontent.com/35858975/112390192-c5cc3680-8d5a-11eb-91fe-3ba76d88caee.png)

2021-03-25 01:04 UTC, mark-prins commented on src/widgets/modalChildren/ADRInput.js
> +          setForm({ form: changed.formData, isValid: validator(changed.formData) });
```suggestion
          setForm({ formData: changed.formData, isValid: validator(changed.formData) });
```

2021-03-25 01:45 UTC, mark-prins requested changes
A typo in the `ADRInput` - with that changed, it's all working for me!

2021-03-25 01:49 UTC, joshxg commented
🙄 sorry again 🤣

2021-03-25 01:51 UTC, mark-prins approved these changes
🎉

2021-03-25 01:52 UTC, mark-prins commented
> 🙄 sorry again 🤣

I appreciated it.. makes me feel like I'm being useful

2021-03-26 01:15 UTC, merged