#4387 Set requistion.isRemoteOrder to false by default
openmsupply/mobile pull request #4392
Opened 2021-09-01 09:10 UTC by sworup

## Description

- Fixes #4387
- Set requistion.isRemoteOrder to false by default
- Also remove isRemoteOrder check disabling deletion of requisition if isRemoteOrder is false. Setting isRemoteOrder to false by default would have otherwise disabled deletion of the these newly created requisitions

## Change summary

Explain and justify your changes

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Do something

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

2021-09-06 09:07 UTC, joshxg reviewed
There is existing logic that we can't delete customer requisitions which have been created through sync.

I'm not sure of why this is, exactly, I want to make sure we can remove that logic or if we need to add it back, though (We could check if a customer requisition has a linkedTransaction, and not allow deleting it, if true).

@Chris-Petty - do you know why since forever ago, we have not been able to delete Customer Requisitions from the server?

2021-09-06 09:32 UTC, ujwalSussol reviewed
@sworup This looks good to me. 

I think we need to make a APK for testing.

2021-09-08 11:24 UTC, ujwalSussol commented
@sworup @joshxg  @Chris-Petty  :

I spent 45 minutes with @ArpitaSussol  looking at the current `Requisition - Response`  work flow and it is true that : 

-  `Requisition - Response` that is created via external order is not deletable. 
- `Requisition - Response` that is created in the mobile it self is allowed to be deleted. 

However we have a way to maintain the above workflow in the following manner : 

- we use the field [requisition]linked_requisition_id  to control the delete.
- If  [requisition]linked_requisition_id is empty or blank then the `Requisition - Response` is local and allow delete.
- if  [requisition]linked_requisition_id has a 'UUID' data then this is a external data and we don't allow delete. 
- Problem solved : We no longer need to rely on field `isRemoteOrder`

2021-09-10 04:35 UTC, joshxg requested changes

2021-09-10 04:35 UTC, joshxg commented on src/database/DataTypes/Requisition.js
> +    linkedRequisition: { type: 'string', optional: true },
This won't work for historic requisitions, you would need to create migration code to send a message to the server saying the mobile site has upgraded, then have the server send all customers requisitions back to all mobile sites so we can save the id of the linked requisition.

An easier solution is to use `linkedTransaction`. All customer requisitions which have come from the server will have a `linkedTransaction` on mobile, while manually created ones on the mobile site itself will not.

This means we won't need to create migration code, nor will we need to add this field

2021-09-10 07:30 UTC, ujwalSussol commented
@joshxg   if `linkedTransaction` is set on the cloud for  requistion.respose  form even when CI is not created then using this field will be OK. 

@sworup  :  you will need to do a requisition work flow to work out when  `linkedTransaction` is set.

2021-12-08 20:30 UTC, katherine-sussol commented
Hi @sworup! Would you want to look at addressing the changes requested for this one or would you prefer to have someone else take a look? (just wary this PR/issue has been open for a while and would be good to close it out)

2021-12-09 04:07 UTC, sworup commented
@katherine-sussol I am on paternity leave till 24th December so I might not be able to look into this right away.

2021-12-09 22:46 UTC, Chris-Petty commented
@sworup omg congrats!

2022-02-22 06:07 UTC, sworup commented
# About trans lines not showing in desktop after syncing when new customer requisition is created

- Here is a screenshot of the single requisition thus created, its transaction record and trans_line records in realm database:
![Screen Shot 2022-02-18 at 4 57 07 PM](https://user-images.githubusercontent.com/683452/154673360-bf23627a-a3ef-4c5e-abed-274196413cb7.jpg)
  - Notice here the `transactionItem inside createTransactionItem`'s id and `transaction inside createTransactionItem`'s id. The `transaction` id is same as `transactionItem` id and also the 4 `transactionItem` lines have same id. There is a `generateUUID()` method inside `createTransactionItem` that should have generated unique IDs but it is not. I think that what causes the records to no sync back to desktop hence causing the missing lines.

2022-02-22 06:41 UTC, sworup commented
@Chris-Petty 
I talked with @ujwalSussol sir and we have come to this conclusion:

- In case of conversion, we should probably do a check during store site conversion. If it is mobile store, we do not allow conversion until these suggested customer requisitions are handled. They should either be deleted or finalised. Ask the users to handle it and give them a choice to allow mSupply to delete these requisitions. This what I think, @mark-prins did to handle this issue months ago, he asked the client to do it, maybe we should put this in code during desktop to mobile site conversion.
- We do have an SG response requisition creating linked CI issue in mobile though. https://github.com/openmsupply/mobile/issues/4592

2022-04-07 00:33 UTC, katherine-sussol commented
Closing as per comments:
- https://github.com/openmsupply/mobile/pull/4392#issuecomment-1047473397
- https://github.com/openmsupply/mobile/issues/4387#issuecomment-1056245005 
 
Desktop issue:
https://github.com/sussol/msupply/issues/10490

(thanks @sworup for all the investigation!)

2022-04-07 00:33 UTC, closed without merging