#4785 Update date-picker to properly set initialValue
openmsupply/mobile pull request #4786
Opened 2022-07-05 07:56 UTC by sworup

- Also take the same value format for all

Fixes #?

## Change summary

Explain and justify your changes

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Do something

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

2022-07-08 00:47 UTC, sworup commented
This is still in draft.
There is a problem where after update vax event listing will still show older date.
Working on it.

2022-07-12 08:28 UTC, sworup commented
@chastichno this is ready to review, it fixes the datepicker issue, other bugs I would create other issues to fix.

2022-07-13 22:34 UTC, chastichno requested changes
@sworup With the changes made in this PR users are no longer able to enter the Date from the keyboard

2022-07-19 05:26 UTC, sworup commented on src/widgets/JSONForm/widgets/DatePicker.js
> +    const expectedFormateDate = alternateFormatDate.isValid()
Resolved with e9afe902

2022-07-20 00:18 UTC, chastichno requested changes
When I manually erase the date form the input field I get a Warning:
<img width="1289" alt="Screen Shot 2022-07-20 at 12 17 40 PM" src="https://user-images.githubusercontent.com/41636693/179869355-52397120-1e4c-437b-8c4c-ab1b56652ab4.png">

2022-07-20 00:22 UTC, chastichno commented on src/widgets/JSONForm/widgets/DatePicker.js
> +  const [selectedDate, setSelectedDate] = useState('');
```suggestion
  const [selectedDate, setSelectedDate] = useState(Date());
```

2022-07-22 10:51 UTC, sworup commented on src/widgets/JSONForm/widgets/DatePicker.js
> +  const [selectedDate, setSelectedDate] = useState('');
Resolve with b0d9bf68

2022-07-24 23:26 UTC, chastichno approved these changes
Looks good to me! 🙌✨

2022-07-24 23:26 UTC, merged