#4888 Fix app crashes on tapping save changes button multiple times
openmsupply/mobile pull request #4899
Opened 2022-08-19 09:17 UTC by sworup

Fixes #4888

## Change summary

Fixes app crashes on tapping save changes button multiple times

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Do something

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

2022-08-22 04:06 UTC, chastichno requested changes
Right after I select the vaccination event in the patient history, it shows me that there are no json forms for the vaccination event, but it disappears after I click once anywhere:

https://user-images.githubusercontent.com/41636693/185837464-4f87f14c-4a19-48cf-8952-f2326f10ca98.mov

I expect it to work as before - forms should load right away after selecting a vaccination event. With this requesting changes

2022-08-22 04:27 UTC, sworup commented
> Right after I select the vaccination event in the patient history, it shows me that there are no json forms for the vaccination event, but it disappears after I click once anywhere:

@chastichno I moved the variables inside state. You do not need to click again to trigger form load, this was the component on loading state. I guess this is annoying enough that it needs fix. I will work on it. Does rest of the logic look good???

2022-08-22 04:38 UTC, chastichno commented
@sworup Thank you Sworup. Yes, the rest looks good (except for the buttons on which I commented)

2022-08-22 08:19 UTC, sworup commented on src/widgets/modals/VaccinationEvent.js
> +          disabled={!(!!surveySchema && !!surveyForm)}
Resolved with [e82adf2](https://github.com/openmsupply/mobile/pull/4899/commits/e82adf2bd3cdff1418a5f5b1e6e50a70cf1f1cfc)

2022-08-23 09:05 UTC, sworup commented
> I still have the same problem with loading the forms. I think it is not a good idea to show users the "No form found" page while it's loading as it looks quite alarming. Can we use a "loading" page instead?

@chastichno resolved with [e2580eb](https://github.com/openmsupply/mobile/pull/4899/commits/e2580eb974fd1496454ccadae285fdaf55acc34b)

2022-08-23 22:37 UTC, chastichno approved these changes
Looks great! Needs to be properly tested though

2022-08-26 05:30 UTC, merged