#5239 set some more mandatory fields
openmsupply/mobile pull request #5266
Opened 2023-07-17 08:45 UTC by arjunSussol

Set some more mandatory fields for patient and prescriber.

Fixes #5239 

## Change summary

Explain and justify your changes

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Better to set up mobile with Kiribati data
- [ ] On desktop, open record browser > go to `form_schema` table and its json_schema and ui_schema fields.
- [ ] For schema update I have the json file locally also we have a private repo for it. So, please contact me.
- [ ] The required fields that set mandatory are listed here: https://docs.google.com/spreadsheets/d/1TxGC30J7qJOqOQz_L2L62BTt8URho4-1JS4NS_g_RFM/edit?pli=1#gid=1122312565
- [ ] You must give or select a valid value for above fields to create/update the patient/prescriber.

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

2023-07-17 10:33 UTC, arjunSussol commented
![](https://github.trello.services/images/mini-trello-icon.png) [(4.1.4.b) Prevent user from omitting mandatory information](https://trello.com/c/KhoHdBO9/109-414b-prevent-user-from-omitting-mandatory-information)

2023-07-18 05:16 UTC, AnushaUp commented
## Testing
Tested in `v8.6.6-rc3` Test APK
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Better to set up mobile with Kiribati data
- [ ] On desktop, open record browser > go to `form_schema` table and query by type `PatientSurvey`. Its json_schema and ui_schema fields needs to be updated
- [ ] For json_schema update use the text from: 
[KiriJsonSchema.txt](https://github.com/openmsupply/mobile/files/12068452/KiriJsonSchema.txt)
- [ ] For ui_schema update use the text from: 
[KiriUISchema.txt](https://github.com/openmsupply/mobile/files/12068471/KiriUISchema.txt)
- [ ] If you still struggle with the schema update then please let me know, I will help you.
- [ ] The required fields that set mandatory are listed here: https://docs.google.com/spreadsheets/d/1TxGC30J7qJOqOQz_L2L62BTt8URho4-1JS4NS_g_RFM/edit?pli=1#gid=1122312565
- [ ] On mobile, you must give or select a valid value for above fields to create/update the patient/prescriber.
- [ ] After approval and merger of this PR, I will update those schema to our [private repo](https://github.com/sussol/client-JSON-schemas/tree/main/Kiribati/COVID-19-vaccination-rollout)

2023-07-18 10:00 UTC, AnushaUp commented
> * On mobile, you must give or select a valid value for above fields to create/update the patient/prescriber.
Its creating problems for dispensing vaccine for the patients from other store. It does not let you move forward if the mandatory fields are empty and can't let you input in the fields also.

2023-07-24 04:34 UTC, sanjeevsussol commented
@anildahalsussol - can you do the review?

2023-07-24 06:41 UTC, anildahalsussol commented on src/utilities/formInputConfigs.js
> +    invalidMessage: `${formInputStrings.gender_must_be_selected}`,
@arjunSussol : Me and @AnushaUp tested and saw this msg is not showing up.

2023-07-24 06:43 UTC, anildahalsussol requested changes
Tested with @AnushaUp : Apart from that, we got some flaw regarding json schema like 
Previous serious allergic reactions?: Not shown as required in the UI and also it has default value. Similarly for Previous adverse events following immunisation

2023-07-24 06:44 UTC, anildahalsussol commented
> > * On mobile, you must give or select a valid value for above fields to create/update the patient/prescriber.
> 
> Its creating problems for dispensing vaccine for the patients from other store. It does not let you move forward if the mandatory fields are empty and can't let you input in the fields also.

@adamdewey @arjunSussol: Are we okay with this one?

2023-07-25 01:31 UTC, adamdewey commented
> @adamdewey @arjunSussol: Are we okay with this one?

No, we can't release like this unfortunately. 

I was talking to @DhanyaHerath earlier - we were thinking that we could put these changes behind a global preference - so that only the K client could use them. Would that be an option?

2023-07-25 04:44 UTC, arjunSussol commented
> > @adamdewey @arjunSussol: Are we okay with this one?
> 
> No, we can't release like this unfortunately.
> 
> I was talking to @DhanyaHerath earlier - we were thinking that we could put these changes behind a global preference - so that only the K client could use them. Would that be an option?

Hi @adamdewey even if we add the store preference as you mentioned then still the issue will be raised for the Kiribati sites. One can't dispense vaccine to patient of another store.

2023-07-25 04:47 UTC, DhanyaHerath commented
@arjunSussol Oh, I see what you mean, though catch me up a little - does this get checked every time you dispense? Not when you are creating the patient itself?

2023-07-25 05:01 UTC, arjunSussol commented
Hi @DhanyaHerath yes, it will be checked every time when dispensed to a patient from different store.

2023-07-25 06:26 UTC, arjunSussol commented
> Tested with @AnushaUp : Apart from that, we got some flaw regarding json schema like Previous serious allergic reactions?: Not shown as required in the UI and also it has default value. Similarly for Previous adverse events following immunisation

@anildahalsussol @AnushaUp Have you updated the form_schema as described in the PR description?

2023-07-25 06:45 UTC, AnushaUp commented
> > Tested with @AnushaUp : Apart from that, we got some flaw regarding json schema like Previous serious allergic reactions?: Not shown as required in the UI and also it has default value. Similarly for Previous adverse events following immunisation
> 
> @anildahalsussol @AnushaUp Have you updated the form_schema as described in the PR description?

@anildahalsussol @arjunSussol Yeah it was due to the json field not updated properly😅

2023-07-25 06:56 UTC, AnushaUp commented
Moving this to done as per the discussion

2023-07-25 12:07 UTC, arjunSussol commented
> > @adamdewey @arjunSussol: Are we okay with this one?
> 
> No, we can't release like this unfortunately.
> 
> I was talking to @DhanyaHerath earlier - we were thinking that we could put these changes behind a global preference - so that only the K client could use them. Would that be an option?

@adamdewey @DhanyaHerath I have set the preference in the mobile side, by default it will be `False`.
We can create footrunner for Kiribati and set it to `True`, then validation will work accordingly.
Fixed by https://github.com/openmsupply/mobile/pull/5266/commits/74eaa9f3053bb627a80f71cf42af7dd55597689f

@anildahalsussol @AnushaUp I will create a release version once approved this PR.
Please, make sure that you have updated the `form_schema` before testing this.
Also, we may need a foot-runner for Kiribati data.

2023-08-08 21:32 UTC, JonnaQuismundo commented
Hi @anildahalsussol can you re-review? Thanks!

2023-08-10 06:17 UTC, anildahalsussol approved these changes
Looks good. Will test once apk is built.

2023-08-10 06:58 UTC, merged